---
apiVersion: v1
kind: Service
metadata:
 name: shopfront-consul
 annotations:
   getambassador.io/config: |
     ---
     apiVersion: ambassador/v1
     kind: Mapping
     name: shopfront_consul
     prefix: /shopfront/
     service: shopfront
     resolver: consul-dc1
     load_balancer:
       policy: round_robin
spec:
 ports:
 - name: http
   port: 80
