# NB: ClusterRoles and ClusterRoleBindings are not namespaced

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
rules:
# Regular Ambassador OSS access requirements
- apiGroups: [""]
  resources: 
  - endpoints
  - namespaces
  #- secrets # commented out; see below
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: 
  - customresourcedefinitions
  verbs: ["get", "list", "watch"]
- apiGroups: ["getambassador.io"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]
# Ambassador Pro access requirements.  Also gets "create" for secrets.
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get", "list", "watch", "create"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: default
