---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    enable_grpc_web: true
    default_label_domain: ambassador
    default_labels:
      ambassador:
        defaults:
        - x_limited_user:
            header: "x-limited-user"
            omit_if_not_present: true
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: tls
spec:
  config:
    server:
      enabled: True
      redirect_cleartext_from: 8080
      alpn_protocols: h2
