# @TEMPLATE@
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: qotm-limited
spec:
  prefix: /qotm/limited/
  rewrite: /limited/
  service: qotm
  labels:
    ambassador:
      - request_label:
        - qotm
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: qotm-open
spec:
  prefix: /qotm/open/
  service: qotm
---
apiVersion: v1
kind: Service
metadata:
  name: qotm
spec:
  selector:
    app: qotm
  ports:
  - port: 80
    name: http-qotm
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qotm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qotm
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:{{env "QOTM_VERSION"}}
        ports:
        - name: http-api
          containerPort: 5000
        env:
        - name: REQUEST_LIMIT
          value: "5"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
