---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: qotm-consul
spec:
  prefix: /qotm-consul/
  service: qotm-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
---
apiVersion: v1
kind: Service
metadata:
  name: qotm-consul
spec:
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotm-consul
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: qotm-consul
  template:
    metadata:
      labels:
        app: qotm-consul
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:1.7
        ports:
        - name: http-api
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
