---
apiVersion: v1
kind: Service
metadata:
  name: jwt-httpbin
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  jwt_httpbin_mapping
      prefix: /jwt-httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org 
spec:
  ports:
  - name: httpbin
    port: 80
