{
 "title": "Ambassador",
 "description": "Ambassador dashboard for Prometheus",
 "tags": [ "ambassador" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "listener_port", "label": "Listener port", "query": "8443" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "cluster_ingress:envoy_http_ingress_http_downstream_rq_total:rate1m",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Peak RPS Percentiles",
   "type": "graph",
   "description": "95th, 90th, and 50th percentile of total requests per second through Ambassador",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95, cluster_ingress:envoy_http_ingress_http_downstream_rq_total:rate1m[1h])",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "quantile_over_time(0.9, cluster_ingress:envoy_http_ingress_http_downstream_rq_total:rate1m[1h])",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "quantile_over_time(0.5, cluster_ingress:envoy_http_ingress_http_downstream_rq_total:rate1m[1h])",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Peak 95% Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "quantile_over_time(0.95, cluster_ingress:envoy_http_ingress_http_downstream_rq_total:rate1m[1h])"
    }
   ]
  },
  { "title": "Listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "API Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_2xx[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_3xx[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_4xx[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_5xx[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_80_http_ingress_http_downstream_rq_2xx[1m]))"
    },
    {}
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.5\"}",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Downstream Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_http1_total[1m]))",
     "legendFormat": "HTTP/1.1"
    },
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_http2_total[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_websocket_total[1m]))",
     "legendFormat": "WebSocket"
    }
   ]
  },
  {
   "title": "Registered Services",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "envoy_cluster_manager_active_clusters"
    },
    {}
   ]
  }
 ]
}