---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-py
  name: grpc-py
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: grpc_demo_mapping
      port: 5555
      service: grpc-py
spec:
  type: ClusterIP
  ports:
  - name: grpc-greet
    port: 80
    targetPort: grpc-api
  selector:
    service: grpc-py
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-py
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: grpc-py
    spec:
      containers:
      - name: grpc-py
        image: datawire/grpc_demo:0.1
        imagePullPolicy: Always
        ports:
        - name: grpc-api
          containerPort: 50052
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
