# @TEMPLATE@

######################################################################
# Configure Ambassador OSS to use Ambassador Pro.
---
apiVersion: getambassador.io/v1
kind: RateLimitService
metadata:
  name: ambassador-pro-ratelimit
spec:
  service: ambassador-pro:80
---
apiVersion: getambassador.io/v1
kind: AuthService
metadata:
  name: ambassador-pro-auth
spec:
  proto: grpc
  auth_service: ambassador-pro:80
  allow_request_body: false # setting this to 'true' allows Plugin and External filters to access the body, but has performance overhead
---
apiVersion: ambassador/v1
kind: Mapping
metadata:
  name: ambassador-pro
spec:
  prefix: /.ambassador/
  rewrite: ""
  service: ambassador-pro:80
---
# DevPortal
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: ambassador-pro-devportal
spec:
  prefix: /docs/
  rewrite: ""
  service: ambassador-pro:80
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: ambassador-pro-devportal-api
spec:
  prefix: /openapi/
  rewrite: ""
  service: ambassador-pro:80
---
apiVersion: getambassador.io/v1beta2
kind: FilterPolicy
metadata:
  name: ambassador-pro-internal-access-control
spec:
  rules:
    - host: "*"
      path: "*/.ambassador-internal/*"
      filters:
        - name: ambassador-pro-internal-access-control
---
apiVersion: getambassador.io/v1beta2
kind: Filter
metadata:
  name: ambassador-pro-internal-access-control
spec:
  Internal: {}
---
--
# This mapping needs to exist, but is never actually followed.
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: callback_mapping
spec:
  prefix: /callback
  service: NoTaReAlSeRvIcE

######################################################################
# Create the 'ambassador-pro' Service.
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-pro
  name: ambassador-pro
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    service: ambassador-pro

######################################################################
# Create the Deployment backing the 'ambassador-pro' Service.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ambassador-pro
  template:
    metadata:
      labels:
        service: ambassador-pro
    spec:
      serviceAccountName: ambassador-pro
      terminationGracePeriodSeconds: 0
      containers:
      - name: ambassador-pro
        image: quay.io/datawire/ambassador_pro:amb-sidecar-{{env "AMBASSADOR_PRO_VERSION"}}
        ports:
        - name: http
          containerPort: 8500
        env:
        - name: APP_LOG_LEVEL
          value: "debug"
        - name: REDIS_URL 
          value: ambassador-pro-redis:6379
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: AMBASSADOR_LICENSE_KEY 
          value: {{env "AMBASSADOR_LICENSE_KEY"}}
        # DevPortal settings
        # Set this to the address that Ambassador is externally-reachable from
        - name: AMBASSADOR_URL
          value: {{env "AMBASSADOR_URL"}}
        # Set this to the address that Ambassador is internally reachable from
        - name: AMBASSADOR_INTERNAL_URL
          value: {{env "AMBASSADOR_INTERNAL_URL"}}
        # Set this to the address that Ambassador admin is internally reachable from
        - name: AMBASSADOR_ADMIN_URL
          value: {{env "AMBASSADOR_ADMIN_URL"}}
        # To customize content and look&feel fork this repo and point to it
        - name: APRO_DEVPORTAL_CONTENT_URL
          value: {{env "APRO_DEVPORTAL_CONTENT_URL"}}
        # Change this if you want different poll rate for getting OpenAPI docs:
        - name: POLL_EVERY_SECS
          value: "60"
