---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: microdonut
spec:
  prefix: /microdonut/
  service: microdonut
---
apiVersion: v1
kind: Service
metadata:
  name: microdonut
  labels:
    app: microdonut
spec:
  type: ClusterIP
  selector:
    app: microdonut
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10001
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microdonut
  labels:
    app: microdonut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microdonut
  template:
    metadata:
      labels:
        app: microdonut
    spec:
      containers:
      - name: microdonut
        image: danielbryantuk/microdonut:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 10001
        livenessProbe:
          httpGet:
            path: /
            port: 10001
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: tracing-config
