apiVersion: getambassador.io/v1beta1
kind: RateLimit
metadata:
  name: basic-rate-limit
spec:
  domain: ambassador
  limits:
   - pattern: [{generic_key: "qotm"}]
     rate: 5
     unit: minute
   - pattern: [{generic_key: "qotm"}]
     rate: 5
     unit: minute